apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: yandex/clickhouse-server:latest
        ports:
        - containerPort: 9000
        - containerPort: 8123
        env:
        - name: user
          value: "admin"
        - name: password
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: clickhouse
